### ISSUE TITLE
[jsx3] avatar size string support

### ISSUE THREAD

**Issue by Enalmada** [Enalmada/bs-ant-design#3]
Would be ideal to figure out how to allow this if reason can support it.

**Comment by JakubMarkiewicz** [comment]
Do you mean number support?
According to docs avatar size supports ` number | string: large small default `, string is already covered with  polymorphic variant like so ```<Avatar size=`large />```
I've tested support for number, didn't notice any issues so far. It would be called little differently, for string
```<Avatar size=Size(`large) />``` for number `<Avatar size=Int(50) />`.

**Comment by Enalmada** [comment]
Oh interesting...I was just running through my test environment and had something like this `<Avatar size={64}  />` and it didn't work but I will try again later tonight with the way you are doing for number!

**Comment by JakubMarkiewicz** [comment]
@Enalmada I will push it now, wasn't sure if you referred to string or number :)
Previously number wasn't supported, added it just now

**Comment by Enalmada** [comment]
Ya sorry...that description was so poorly lacking description.  I knew if I didn't make a quick note as I was testing out stuff I would forget all about it but will be much more descriptive next time.

**Comment by JakubMarkiewicz** [comment]
No worries, i figured it was probably about number :)
It's live on 2.0.0-alpha.11

**Comment by JakubMarkiewicz** [comment]
Here's snippet if you're interested
```OCAML
[@bs.deriving jsConverter]
type sizeType = [ | `small | `default | `large];
type size =
  | Int(int)
  | Size(sizeType);

module AvatarSize = {
  type t;
  external int: int => t = "%identity";
  external size: string => t = "%identity";
};

let setAvatarSize = (a: size) =>
  switch (a) {
  | Int(int) => AvatarSize.int(int)
  | Size(avatarSize) => avatarSize |> sizeTypeToJs |> AvatarSize.size
  };
```

**Comment by Enalmada** [comment]
Oh nice!  There are quite a few places where antd lets you pass different types and I had no idea how to handle it.  This is very helpful.
